### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by jalpa015** [jalpa015/ml-webApp#3]
Web App UI needs to be enhanced.

**Comment by jalpa015** [comment]
Few points that needs to be fixed for enhancement are - 
1. CSS issue (the red box length is not same as canvas length; adding colors for different sections so it is easy to understand)
2. Adding more information to make a user know what they can explore on the website

**Comment by jalpa015** [comment]
@arun-esh Would you be interested?

**Comment by arun-esh** [comment]
@jalpa015 sure, Please assign to me.
